/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Ai: () => import('#controllers/ai_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Projects: () => import('#controllers/projects_controller'),
}
